<a href="https://colab.research.google.com/github/AndriuGJ/EjercicioPractico1/blob/main/PracticaCalificada1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRACTICA CALIFICADA 1

In [1]:
import numpy as np

1: Resolver con Numpy los siguientes casos:

In [2]:
#1 Crear un vector de numeros enteros del 1 al 20
vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#2 Crear una matriz de 3x3 con valores aleatorios de 0 y 1
matriz = np.random.randint(0, 2, size=(3, 3))
print(matriz)

[[1 0 1]
 [0 0 0]
 [0 0 0]]


In [4]:
#3 Redimendionar una matriz 4x4 a una 2x8
matriz_4x4 = np.random.randint(1, 10, size=(4, 4))
matriz_2x8 = matriz_4x4.reshape(2, 8)
print(matriz_2x8)

[[4 5 5 6 9 4 9 5]
 [4 4 7 8 2 2 6 7]]


In [6]:
#4 Crear una matriz de 10 equidistante
matriz_10 = np.random.randint(0, 2, size=(10, 10))
print(matriz_10)

[[1 1 1 0 1 1 1 1 1 0]
 [1 1 0 1 0 0 1 1 1 0]
 [1 0 0 1 1 1 1 1 1 1]
 [1 1 0 0 1 0 1 1 0 0]
 [1 1 1 0 0 0 0 0 1 1]
 [0 1 1 1 1 0 0 0 1 1]
 [1 0 1 1 0 1 1 1 1 0]
 [1 1 0 0 1 1 0 0 1 0]
 [0 0 1 1 0 0 0 1 1 1]
 [1 1 1 1 1 1 0 0 0 0]]


In [15]:
#5 Concatenar 2 vectores uno vertical y el otro horizontal
vertical = np.random.randint(1,10, size=(1,4))
horizontal = np.random.randint(1,10, size=(4,1))
print(vertical)
print(horizontal)
print('=======CONCATENADO=======')
print(np.concatenate((vertical.T, horizontal), axis=0))

[[7 9 8 2]]
[[9]
 [2]
 [7]
 [5]]
=======CONCATENADO=======
[[7]
 [9]
 [8]
 [2]
 [9]
 [2]
 [7]
 [5]]


2: Resolver las siguientes operaciones

In [17]:
#1 Calculamos la suma, resta, multiplicacion y divicion de 2 vectores
vector1 = np.random.randint(1,10, size=(1,4))
vector2 = np.random.randint(1,10, size=(1,4))
print(vector1)
print(vector2)
print('=======SUMA=======')
print(vector1 + vector2)
print('=======RESTA=======')
print(vector1 - vector2)
print('=======MULTIPLICACION=======')
print(vector1 * vector2)

[[2 1 5 4]]
[[9 6 2 4]]
=======SUMA=======
[[11  7  7  8]]
=======RESTA=======
[[-7 -5  3  0]]
=======MULTIPLICACION=======
[[18  6 10 16]]


In [25]:
#2 Calculamos la media, mediana, desviacion estandar
vector = np.array([4, 3, 3, 4, 5,7,9,12,15])
media = np.mean(vector)
mediana = np.median(vector)
desviacion_estandar = np.std(vector)
print(vector)
print("Media: ",media,"Mediana:",mediana,"Desviacion estandar: ", desviacion_estandar)

[ 4  3  3  4  5  7  9 12 15]
Media:  6.888888888888889 Mediana: 5.0 Desviacion estandar:  4.039924213932854


In [26]:
#3 Normaliza un vector dividiendo cada elemento por le valor maximo
vector = np.array([4, 3, 3, 4, 5,7,9,12,15])
vector_normalizado = vector / np.max(vector)
print(vector_normalizado)

[0.26666667 0.2        0.2        0.26666667 0.33333333 0.46666667
 0.6        0.8        1.        ]


In [28]:
#4 Buscar el indice del valor maximo y minimo
vector = np.array ([16,6,8,1,12,5,6])
indice_maximo = np.argmax(vector)
indice_minimo = np.argmin(vector)
print(vector)
print("Maximo: ", indice_maximo, "Minimo: ", indice_minimo)

[16  6  8  1 12  5  6]
Maximo:  0 Minimo:  3


In [31]:
#5 Realizar un multiplicacion matricial de 2 matrices 3x3
matriz1 = np.random.randint(1,10, size=(3,3))
matriz2 = np.random.randint(1,10, size=(3,3))
print(matriz1)
print(matriz2)
print('=======MULTIPLICACION=======')
print(np.dot(matriz1, matriz2))


[[3 8 1]
 [2 3 4]
 [4 2 1]]
[[4 7 5]
 [1 3 4]
 [3 7 3]]
=======MULTIPLICACION=======
[[23 52 50]
 [23 51 34]
 [21 41 31]]


3: Resolver con Numpy los siguientes casos

In [42]:
#1 Elementos par del vector
vector = np.array([4, 3, 3, 4, 5,7,9,12,15])
pares = {}
for i in range(len(vector)):
    if vector[i] % 2 == 0:
        pares[i] = vector[i]
print(vector)
print("Los elementos pares del vector son: ", pares)

[ 4  3  3  4  5  7  9 12 15]
Los elementos pares del vector son:  {0: np.int64(4), 3: np.int64(4), 7: np.int64(12)}


In [48]:
#2 Numeros mayores a 5
vector = np.array([3,5,7,21,3,5,1,56,34,52,75])
mayores_a_5= {}
for i in range(len(vector)):
    if vector[i] > 5 :
        mayores_a_5[i] = int(vector[i])
print(vector)
print(mayores_a_5)

[ 3  5  7 21  3  5  1 56 34 52 75]
{2: 7, 3: 21, 7: 56, 8: 34, 9: 52, 10: 75}


In [57]:
#3 Valores iguales a 0
vector = np.random.randint(0, 5, size=10)
negativos = {}
for i in range(len(vector)):
    if vector[i] == 0:
        negativos[i] = int(vector[i])
print("Vector generado:", vector)
print("Los elementos iguales a 0 son: ", negativos)

Vector generado: [4 2 4 4 0 3 1 0 3 0]
Los elementos iguales a 0 son:  {4: 0, 7: 0, 9: 0}


In [58]:
#4 Filtar valores negativos
vector = np.array([-3,5,7,-21,3,-5,-1,56,34,52,75])
negativos ={}
for i in range(len(vector)):
  if vector[i] < 0:
    negativos[i] = int(vector[i])
print(vector)
print(negativos)

[ -3   5   7 -21   3  -5  -1  56  34  52  75]
{0: -3, 3: -21, 5: -5, 6: -1}


In [64]:
#5 Sacamos la media
vector = np.random.randint(45, 100, size=10)
mayores = {}
for i in range(len(vector)):
    if vector[i] > 50:
        mayores[i] = int(vector[i])
print(vector)
print(mayores)
#Sacacamos la media de los numeros mayores a 50
media = np.mean(list(mayores.values()))
print("La media de los numeros mayores a 50 es: ", media)


[98 88 83 80 68 67 89 74 73 85]
{0: 98, 1: 88, 2: 83, 3: 80, 4: 68, 5: 67, 6: 89, 7: 74, 8: 73, 9: 85}
La media de los numeros mayores a 50 es:  80.5


4: Resolver con Numpy los siguientes casos

In [67]:
#1 Crear un vector de 10 elementos y los numeros iguales a 5 rempalzarlos con 0
vector = np.random.randint(0, 10, size=10)
print("Vector Inicial: ",vector)
for i in range(len(vector)):
    if vector[i] == 5:
        vector[i] = 0
print(vector)

Vector Inicial:  [6 4 7 0 7 2 4 1 7 5]
[6 4 7 0 7 2 4 1 7 0]


In [68]:
#Combinar 2 vectores boleanos usando and y or
vector1 = np.array([True, False, True, True])
vector2 = np.array([False, True, False, True])
print(vector1)
print(vector2)
print('=======AND=======')
print(np.logical_and(vector1, vector2))
print('=======OR=======')
print(np.logical_or(vector1, vector2))


[ True False  True  True]
[False  True False  True]
=======AND=======
[False False False  True]
=======OR=======
[ True  True  True  True]


In [69]:
#Contar los valores de un vector que son multilplos de 3
vector = np.array([3,5,7,21,3,5,1,56,34,52,75])
multiplos_de_3 = {}
for i in range(len(vector)):
  if(vector[i] %3 == 0):
    multiplos_de_3[i] = int(vector[i])
print(vector)
print("Los multiplos de 3 son: ",multiplos_de_3)

[ 3  5  7 21  3  5  1 56 34 52 75]
Los multiplos de 3 son:  {0: 3, 3: 21, 4: 3, 10: 75}


In [70]:
#Encontramos los indices de los elementos nulos en un vector usando np.nonzero
vector= np.array([1,2,3,4,0,5,0,0,0])
indices_nulos = np.nonzero(vector == 0)
print(vector)
print("Los indices de los elementos nulos son: ",indices_nulos)

[1 2 3 4 0 5 0 0 0]
Los indices de los elementos nulos son:  (array([4, 6, 7, 8]),)
